In [12]:
import pandas as pd
import numpy as np

# 建立模擬的髒數據：有重複項、有空值(None/NaN)、有不合理的異常值
dirty_data = {
    'Patient_ID': ['P-001', 'P-002', 'P-003', 'P-004', 'P-001'],  # P-001 重複了
    'Age': [26, 45, None, 32, 26],                                # P-003 年齡缺失
    'Blood_Glucose': [90, 999, 140, 95, 90],                      # P-002 血糖 999 是異常值
    'Treatment': ['A', 'B', 'A', 'B', 'A']
}

# 建立數據表格
df_dirty = pd.DataFrame(dirty_data)
print("--- 原始髒數據 ---")
df_dirty.head()

# 今日任務
# 1. 去除重複項
# 2. 處理異常值：將血糖 > 500 的視為雜訊，標記為 NaN
# 3. 填補缺失值：用該欄位的平均值 (Mean) 填補

--- 原始髒數據 ---

  Patient_ID   Age  Blood_Glucose Treatment
0      P-001  26.0             90         A
1      P-002  45.0            999         B
2      P-003   NaN            140         A
3      P-004  32.0             95         B
4      P-001  26.0             90         A

In [22]:
# 任務1. 去除重複項
# 從上到下掃描表格後，把表格裡長得一模一樣的「重複列」刪除
df_cleaned = df_dirty.drop_duplicates()

# 任務2. 處理異常值：將血糖 > 500 的視為雜訊，標記為 NaN
# 先鎖定「血糖 > 500」的那一整列，再來看欄位，只看'Blood_Glucose'這一欄。 loc[列,欄]
# 確定好是哪一行哪一欄位之後，強制把數值改成 = np.nan
df_cleaned.loc[df_cleaned['Blood_Glucose'] > 500, 'Blood_Glucose'] = np.nan

# 任務3. 填補缺失值：用該欄位的平均值 (Mean) 填補
# 利用fillna() 將所有nan值填充你選擇的空值
df_cleaned['Age'] = df_cleaned['Age'].fillna(df_cleaned['Age'].mean())
df_cleaned['Blood_Glucose'] = df_cleaned['Blood_Glucose'].fillna(df_cleaned['Blood_Glucose'].mean())

print("\n--- 清洗後的乾淨數據 ---")
df_cleaned.head()

--- 清洗後的乾淨數據 ---

/var/folders/_m/prklzchj3pz4nrjsgclh4s6h0000gn/T/ipykernel_71599/203588632.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Age'] = df_cleaned['Age'].fillna(df_cleaned['Age'].mean())
/var/folders/_m/prklzchj3pz4nrjsgclh4s6h0000gn/T/ipykernel_71599/203588632.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Blood_Glucose'] = df_cleaned['Blood_Glucose'].fillna(df_cleaned['Blood_Glucose'].mean())

  Patient_ID        Age  Blood_Glucose Treatment
0      P-001  26.000000      90.000000         A
1      P-002  45.000000     108.333333         B
2      P-003  34.333333     140.000000         A
3      P-004  32.000000      95.000000         B

In [24]:
# 1. 去除重複項
df_cleaned = df_dirty.drop_duplicates().copy()

# 2. 處理異常值：將血糖 > 500 的視為雜訊，標記為 NaN
# 幫我定位(location)出『血糖大於500的那一列』，並且找到『血糖』這一欄，把它的值改成 NaN
df_cleaned.loc[df_cleaned['Blood_Glucose'] > 500, 'Blood_Glucose'] = np.nan

# 3. 填補缺失值：用該欄位的平均值 (Mean) 填補
# 為 df_cleaned 是從 df_dirty.drop_duplicates() 誕生出來的。在沒有加上 .copy() 之前，它只是原始資料的「影子」。
df_cleaned['Age'] = df_cleaned['Age'].fillna(df_cleaned['Age'].mean())
df_cleaned['Blood_Glucose'] = df_cleaned['Blood_Glucose'].fillna(df_cleaned['Blood_Glucose'].mean())

print("\n--- 清洗後的乾淨數據 ---")
df_cleaned.head()

## 上一步遇到的錯誤提醒！！
## SettingWithCopyWarning: 
## A value is trying to be set on a copy of a slice from a DataFrame.
## Try using .loc[row_indexer,col_indexer] = value instead
## 最後用.copy()來解決

--- 清洗後的乾淨數據 ---

  Patient_ID        Age  Blood_Glucose Treatment
0      P-001  26.000000      90.000000         A
1      P-002  45.000000     108.333333         B
2      P-003  34.333333     140.000000         A
3      P-004  32.000000      95.000000         B

In [27]:
## 第二題
import pandas as pd

# 建立微型病患數據表
data = {
    'Patient_ID': ['P-001', 'P-002', 'P-003', 'P-004'],
    'Age': [28, 45, 60, 35],
    'Heart_Rate': [75, 115, 85, 105],
    'Risk_Status': ['Normal', 'Normal', 'Normal', 'Normal']
}
df_patients = pd.DataFrame(data)
df_patients.head()

#根據醫學常識，靜止心率超過 100 下/分鐘 (bpm) 屬於心搏過速。請找出 「心率 (Heart_Rate) 大於 100」 的病患，並將他們在 「風險狀態 (Risk_Status)」 欄位的值，精準修改為 'High Risk'。

  Patient_ID  Age  Heart_Rate Risk_Status
0      P-001   28          75      Normal
1      P-002   45         115      Normal
2      P-003   60          85      Normal
3      P-004   35         105      Normal

In [33]:
df_patients.loc[df_patients['Heart_Rate'] > 100, 'Risk_Status'] = 'High Risk'
df_patients.head()

  Patient_ID  Age  Heart_Rate Risk_Status
0      P-001   28          75      Normal
1      P-002   45         115   High Risk
2      P-003   60          85      Normal
3      P-004   35         105   High Risk