今日實戰任務：自動化病患優先級標籤系統

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("healthcare_dataset.csv")
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Tiffany Ramirez,81,Female,O-,Diabetes,2022-11-17,Patrick Parker,Wallace-Hamilton,Medicare,37490.983364,146,Elective,2022-12-01,Aspirin,Inconclusive
1,Ruben Burns,35,Male,O+,Asthma,2023-06-01,Diane Jackson,"Burke, Griffin and Cooper",UnitedHealthcare,47304.064845,404,Emergency,2023-06-15,Lipitor,Normal
2,Chad Byrd,61,Male,B-,Obesity,2019-01-09,Paul Baker,Walton LLC,Medicare,36874.896997,292,Emergency,2019-02-08,Lipitor,Normal
3,Antonio Frederick,49,Male,B-,Asthma,2020-05-02,Brian Chandler,Garcia Ltd,Medicare,23303.322092,480,Urgent,2020-05-03,Penicillin,Abnormal
4,Mrs. Brandy Flowers,51,Male,O-,Arthritis,2021-07-09,Dustin Griffin,"Jones, Brown and Murray",UnitedHealthcare,18086.344184,477,Urgent,2021-08-02,Paracetamol,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,James Hood,83,Male,A+,Obesity,2022-07-29,Samuel Moody,"Wood, Martin and Simmons",UnitedHealthcare,39606.840083,110,Elective,2022-08-02,Ibuprofen,Abnormal
9996,Stephanie Evans,47,Female,AB+,Arthritis,2022-01-06,Christopher Yates,Nash-Krueger,Blue Cross,5995.717488,244,Emergency,2022-01-29,Ibuprofen,Normal
9997,Christopher Martinez,54,Male,B-,Arthritis,2022-07-01,Robert Nicholson,Larson and Sons,Blue Cross,49559.202905,312,Elective,2022-07-15,Ibuprofen,Normal
9998,Amanda Duke,84,Male,A+,Arthritis,2020-02-06,Jamie Lewis,Wilson-Lyons,UnitedHealthcare,25236.344761,420,Urgent,2020-02-26,Penicillin,Normal
9999,Eric King,20,Male,B-,Arthritis,2023-03-22,Tasha Avila,"Torres, Young and Stewart",Aetna,37223.965865,290,Emergency,2023-04-15,Penicillin,Abnormal

In [35]:
#1. 計算全院的「平均醫療費用」

avg_billing = df['Billing Amount'].mean()
print(f"步驟一：全院平均醫療費用為: {avg_billing:.2f} 元")

步驟一：全院平均醫療費用為: 25516.81 元

In [39]:
#2. 先幫所有人預設貼上 'Standard' (標準) 標籤
#利用Pandas的廣播機制 (Broadcasting)讓表格強制加上一欄，並填滿'Standard'
#預設值 (Default Value)」防禦性寫法：先假設所有人都是標準狀態，再把特殊的高風險病人挑出來修改

df['Health_Priority'] = 'Standard'
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Health_Priority
0,Tiffany Ramirez,81,Female,O-,Diabetes,2022-11-17,Patrick Parker,Wallace-Hamilton,Medicare,37490.983364,146,Elective,2022-12-01,Aspirin,Inconclusive,Standard
1,Ruben Burns,35,Male,O+,Asthma,2023-06-01,Diane Jackson,"Burke, Griffin and Cooper",UnitedHealthcare,47304.064845,404,Emergency,2023-06-15,Lipitor,Normal,Standard
2,Chad Byrd,61,Male,B-,Obesity,2019-01-09,Paul Baker,Walton LLC,Medicare,36874.896997,292,Emergency,2019-02-08,Lipitor,Normal,Standard
3,Antonio Frederick,49,Male,B-,Asthma,2020-05-02,Brian Chandler,Garcia Ltd,Medicare,23303.322092,480,Urgent,2020-05-03,Penicillin,Abnormal,Standard
4,Mrs. Brandy Flowers,51,Male,O-,Arthritis,2021-07-09,Dustin Griffin,"Jones, Brown and Murray",UnitedHealthcare,18086.344184,477,Urgent,2021-08-02,Paracetamol,Normal,Standard

In [49]:
# 3. 設定多重條件！
# 關鍵細節：在 Pandas 裡，兩個條件之間要用 & 連結，而且每個條件都必須用小括號 () 包起來！
# Boolean Mask：並非把數據挑出來，而是做出一個核對表（Series 物件），每個都被填入True或False

high_risk_condition = (df['Billing Amount'] > avg_billing) & (df['Age'] > 60)

type(high_risk_condition)
high_risk_condition

0        True
1       False
2        True
3       False
4       False
        ...
9995     True
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [51]:
# 4. 瞄準並覆寫符合條件的人，改成 'High Attention' (高關注)
#把剛剛那份清單用loc的方式找到high_risk_condition=true（默認）的，把他們的Health_Priority都改成High Attention

df.loc[high_risk_condition, 'Health_Priority'] = 'High Attention'
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Health_Priority
0,Tiffany Ramirez,81,Female,O-,Diabetes,2022-11-17,Patrick Parker,Wallace-Hamilton,Medicare,37490.983364,146,Elective,2022-12-01,Aspirin,Inconclusive,High Attention
1,Ruben Burns,35,Male,O+,Asthma,2023-06-01,Diane Jackson,"Burke, Griffin and Cooper",UnitedHealthcare,47304.064845,404,Emergency,2023-06-15,Lipitor,Normal,Standard
2,Chad Byrd,61,Male,B-,Obesity,2019-01-09,Paul Baker,Walton LLC,Medicare,36874.896997,292,Emergency,2019-02-08,Lipitor,Normal,High Attention
3,Antonio Frederick,49,Male,B-,Asthma,2020-05-02,Brian Chandler,Garcia Ltd,Medicare,23303.322092,480,Urgent,2020-05-03,Penicillin,Abnormal,Standard
4,Mrs. Brandy Flowers,51,Male,O-,Arthritis,2021-07-09,Dustin Griffin,"Jones, Brown and Murray",UnitedHealthcare,18086.344184,477,Urgent,2021-08-02,Paracetamol,Normal,Standard
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,James Hood,83,Male,A+,Obesity,2022-07-29,Samuel Moody,"Wood, Martin and Simmons",UnitedHealthcare,39606.840083,110,Elective,2022-08-02,Ibuprofen,Abnormal,High Attention
9996,Stephanie Evans,47,Female,AB+,Arthritis,2022-01-06,Christopher Yates,Nash-Krueger,Blue Cross,5995.717488,244,Emergency,2022-01-29,Ibuprofen,Normal,Standard
9997,Christopher Martinez,54,Male,B-,Arthritis,2022-07-01,Robert Nicholson,Larson and Sons,Blue Cross,49559.202905,312,Elective,2022-07-15,Ibuprofen,Normal,Standard
9998,Amanda Duke,84,Male,A+,Arthritis,2020-02-06,Jamie Lewis,Wilson-Lyons,UnitedHealthcare,25236.344761,420,Urgent,2020-02-26,Penicillin,Normal,Standard
9999,Eric King,20,Male,B-,Arthritis,2023-03-22,Tasha Avila,"Torres, Young and Stewart",Aetna,37223.965865,290,Emergency,2023-04-15,Penicillin,Abnormal,Standard

In [25]:
# 5. 驗收成果報告

print("\n📊 步驟二：標籤貼放完成！以下是全院病患優先級統計：")
print(df['Health_Priority'].value_counts())

📊 步驟二：標籤貼放完成！以下是全院病患優先級統計：
Health_Priority
Standard          8240
High Attention    1760
Name: count, dtype: int64

In [27]:
# 6. 工程師的防呆機制：隨機印出 5 個被標記為 'High Attention' 的病人，親眼核對邏輯對不對

print("\n👀 步驟三：抽查 5 位高關注病患 (確認年齡是否真的 > 60 且 費用 > 平均)：")
display(df[df['Health_Priority'] == 'High Attention'][['Age', 'Billing Amount', 'Health_Priority']].head())

👀 步驟三：抽查 5 位高關注病患 (確認年齡是否真的 > 60 且 費用 > 平均)：

    Age  Billing Amount Health_Priority
0    81    37490.983364  High Attention
2    61    36874.896997  High Attention
6    82    39593.435761  High Attention
21   79    42610.704563  High Attention
26   70    35834.356603  High Attention